### PR TITLE
V2 improvements

### PR DESCRIPTION
**Pull request by viraj124**
- Gas Golfing
- Fix WETH9 integration
- security improvements

### CODE REVIEW

**Review by nnnnicholas — COMMENTED** [review]
well then, this is awesome. reading..

**Review by nnnnicholas — APPROVED** [review]
lgtm

**Comment by nnnnicholas** [comment]
@viraj124 I'm getting this error post-merge. Any idea why? 
image

Can fix temporarily by turning `runOnCompile` off, but I haven't figured out why abi export is broken
image

**Comment by viraj124** [comment]
> @viraj124 I'm getting this error post-merge. Any idea why? image
> 
> Can fix temporarily by turning `runOnCompile` off, but I haven't figured out why abi export is broken image

let me check I thought there was a setup issue on my end

**Comment by nnnnicholas** [comment]
@viraj124 only semi-relevant change i can see is 
image

**Comment by viraj124** [comment]
yeah I did not update this I am also trying to figure why is it throwing an error maybe something to do with the package version not sure

**Comment by viraj124** [comment]
@nnnnicholas it works with this & we don't need the `ERC721` abi specifically so all good I think
```
  abiExporter: {
    path: "../react-app/src/contracts/ABI",
    runOnCompile: true,
    clear: true,
    flat: true,
    only: [],
    spacing: 2,
    except: ["ERC721"],
    pretty: false,
  },
```

**Comment by nnnnicholas** [comment]
Great, will merge this change in via #3. Still weird it's doing this. Maybe @austintgriffith knows why (see https://github.com/austintgriffith/banana-auction/pull/2#issuecomment-1181338785)

**Pull request merged**
